spring:
  profile:
    active: dev # by default active profile is dev, duringh production is replaced by prod by azure environment variable
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80